name: Build CREPL

on:
  push:
    tags:
      - 'v*'  # Run on tag push of pattern v*, like v1.0.0, v20.15.10
  workflow_dispatch:  # Allow manual trigger of workflow

permissions:
  contents: write  # Add explicit permission to create releases

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MinGW using chocolatey
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install mingw -y

      - name: Add MinGW to PATH
        run: echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Check SDL2 directory structure
        run: |
          # Verify the existing directory structure
          Get-ChildItem lib/SDL2
          Get-ChildItem lib/SDL2_ttf
          
          # Verify include paths
          Get-ChildItem lib/SDL2/SDL2-2.32.4/include
          Get-ChildItem lib/SDL2_ttf/SDL2_ttf-2.24.0/include
          
          # Verify library paths
          Get-ChildItem lib/SDL2/SDL2-2.32.4/lib/x64
          Get-ChildItem lib/SDL2_ttf/SDL2_ttf-2.24.0/lib/x64

      - name: Download SDL2 MinGW development libraries
        run: |
          # Download MinGW-compatible SDL2 development libraries
          curl -L https://github.com/libsdl-org/SDL/releases/download/release-2.32.4/SDL2-devel-2.32.4-mingw.zip -o SDL2-mingw.zip
          7z x SDL2-mingw.zip
          
          # Download MinGW-compatible SDL2_ttf development libraries
          curl -L https://github.com/libsdl-org/SDL_ttf/releases/download/release-2.24.0/SDL2_ttf-devel-2.24.0-mingw.zip -o SDL2_ttf-mingw.zip
          7z x SDL2_ttf-mingw.zip
          
          # Create mingw_lib directory to store .a files
          mkdir -p mingw_lib
          
          # Copy the MinGW-compatible library files
          Copy-Item -Path SDL2-2.32.4/x86_64-w64-mingw32/lib/*.a -Destination mingw_lib/
          Copy-Item -Path SDL2_ttf-2.24.0/x86_64-w64-mingw32/lib/*.a -Destination mingw_lib/
          
          # List files in the mingw_lib directory
          Get-ChildItem mingw_lib

      - name: Build with MinGW
        run: |
          mkdir -p build
          cd build
          # First, run CMake without SDL2 flags to ensure compiler check passes
          cmake -G "MinGW Makefiles" ..
          
          # Set environment variables for the full paths to libraries
          $SDL2_LIB = Resolve-Path "../mingw_lib/libSDL2.a"
          $SDL2MAIN_LIB = Resolve-Path "../mingw_lib/libSDL2main.a"
          $SDL2TTF_LIB = Resolve-Path "../mingw_lib/libSDL2_ttf.a"
          
          # Then run cmake again with the SDL2 paths using proper path format for libraries
          cmake -G "MinGW Makefiles" .. `
            -DSDL2_INCLUDE_DIR="../lib/SDL2/SDL2-2.32.4/include" `
            -DSDL2_TTF_INCLUDE_DIR="../lib/SDL2_ttf/SDL2_ttf-2.24.0/include" `
            -DSDL2_LIBRARY="$SDL2_LIB;$SDL2MAIN_LIB" `
            -DSDL2_TTF_LIBRARY="$SDL2TTF_LIB"
          
          # Build the project
          mingw32-make VERBOSE=1

      - name: Create Release Zip
        run: |
          mkdir release
          copy build\crepl.exe release\crepl.exe
          
          # Copy SDL2 DLLs from the MinGW-compatible download
          copy SDL2-2.32.4\x86_64-w64-mingw32\bin\SDL2.dll release\
          copy SDL2_ttf-2.24.0\x86_64-w64-mingw32\bin\SDL2_ttf.dll release\
          copy SDL2_ttf-2.24.0\x86_64-w64-mingw32\bin\zlib1.dll release\
          copy SDL2_ttf-2.24.0\x86_64-w64-mingw32\bin\freetype.dll release\
          
          cd release
          7z a ..\crepl-windows.zip *

      - name: Upload Windows Build
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: crepl-windows.zip
          token: ${{ github.token }}

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SDL2 and SDL2_ttf
        run: sudo apt-get update && sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev

      - name: Build with GCC
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Create Release Tar
        run: |
          mkdir -p release
          cp build/crepl release/crepl
          cd release
          tar -czvf ../crepl-linux.tar.gz *

      - name: Upload Linux Build
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: crepl-linux.tar.gz
          token: ${{ github.token }}